FROM continuumio/miniconda3

COPY . /home/soft/fetch
WORKDIR /home/soft/fetch
RUN conda install -c anaconda numpy \
                              pandas && \
    python setup.py install

WORKDIR /home/soft
RUN git clone https://github.com/devanshkv/pysigproc.git && \
    cd pysigproc && \
    python setup.py install
